- service: httpbin
  default:
    from: httpbin.sso.localtest.me
    to: http://httpbin:8080

- service: hello-world
  default:
    from: hello-world.sso.localtest.me
    to: http://hello-world/

- service: nifi
  default:
    from: nifi.sso.localtest.me
    to: http://nifi.sayari.com:9090

- service: schema-registry
  default:
    from: schema-registry.sso.localtest.me
    to: http://schema-registry.sayari.com:9090/